# Site settings
title: Iźva Komi | Изьватас | Ижемцы
email: nikotapiopartanen@gmail.com
description: > # this means to ignore newlines until "baseurl:"
#baseurl: "izvakomi" # the subpath of your site, e.g. /blog/
url: "langdoc.github.io/izvakomi" # the base hostname & protocol for your site
twitter_username: izvakomi
github_username:  izvakomi

# Build settings
markdown: kramdown
